### ISSUE TITLE
apipie-bindings v0.0.16 not compatible with rest-client 2.x

### ISSUE THREAD

**Issue by bdunne** [Apipie/apipie-bindings#42]
Once v0.0.16 was released we found that Travis builds were failing with the following in the stack trace.
```
Failures:

  1) ManageiqForeman::Connection#fetch with 2 hosts fetches 2 hosts
     Failure/Error: PagedResponse.new(@api.resource(resource).action(action).call(filter))

     ArgumentError:
       wrong number of arguments (2 for 0)
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/abstract_response.rb:71:in `return!'
     # /home/bdunne/.gem/ruby/2.2.4/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:308:in `block in rest_client_call_block'
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:592:in `call'
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:592:in `process_result'
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:504:in `block in transmit'
     # /home/bdunne/.gem/ruby/2.2.4/gems/webmock-1.24.2/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
     # /home/bdunne/.gem/ruby/2.2.4/gems/webmock-1.24.2/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:494:in `transmit'
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:202:in `execute'
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:52:in `execute'
     # /home/bdunne/.gem/ruby/2.2.4/gems/rest-client-2.0.0.rc1/lib/restclient/resource.rb:51:in `get'
     # /home/bdunne/.gem/ruby/2.2.4/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:295:in `call_client'
     # /home/bdunne/.gem/ruby/2.2.4/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:224:in `http_call'
     # /home/bdunne/.gem/ruby/2.2.4/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:174:in `call_action'
     # /home/bdunne/.gem/ruby/2.2.4/gems/apipie-bindings-0.0.16/lib/apipie_bindings/api.rb:169:in `call'
     # /home/bdunne/.gem/ruby/2.2.4/gems/apipie-bindings-0.0.16/lib/apipie_bindings/action.rb:14:in `call'
     # ./lib/manageiq_foreman/connection.rb:49:in `fetch'
     # ./spec/connection_spec.rb:16:in `block (4 levels) in <top (required)>'
     # ./spec/connection_spec.rb:20:in `block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:20:in `block in with_vcr'
     # /home/bdunne/.gem/ruby/2.2.4/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
     # /home/bdunne/.gem/ruby/2.2.4/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /home/bdunne/.gem/ruby/2.2.4/gems/vcr-2.9.3/lib/vcr.rb:182:in `use_cassette'
     # ./spec/spec_helper.rb:19:in `with_vcr'
     # ./spec/connection_spec.rb:19:in `block (4 levels) in <top (required)>'
```
